/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pgy.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author mauriciomora
 */
public class HistorialDeTransferencias extends javax.swing.JFrame {

    /**
     * Creates new form HistorialDeTransferencias
     */
    public HistorialDeTransferencias() {
        initComponents();
        setTitle("West Bank");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        NavbarInicio = new javax.swing.JMenu();
        NavbarTransferir = new javax.swing.JMenu();
        NabvarHistoTrans = new javax.swing.JMenu();
        NabvarSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_transaccion", "Cuenta_origen", "Monto", "Cuenta_destino", "Fecha_hora"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenuBar1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        NavbarInicio.setText("Inicio");
        NavbarInicio.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NavbarInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NavbarInicioMousePressed(evt);
            }
        });
        jMenuBar1.add(NavbarInicio);

        NavbarTransferir.setText("Transferir");
        NavbarTransferir.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NavbarTransferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NavbarTransferirMousePressed(evt);
            }
        });
        jMenuBar1.add(NavbarTransferir);

        NabvarHistoTrans.setText("Historial de transferencias");
        NabvarHistoTrans.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NabvarHistoTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NabvarHistoTransMousePressed(evt);
            }
        });
        jMenuBar1.add(NabvarHistoTrans);

        NabvarSalir.setText("Salir");
        NabvarSalir.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NabvarSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NabvarSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(NabvarSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NavbarInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavbarInicioMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        Inicio inicio = new Inicio();
        inicio.setVisible(true);   
    }//GEN-LAST:event_NavbarInicioMousePressed

    private void NavbarTransferirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavbarTransferirMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        Transferir transferir = new Transferir();
        transferir.setVisible(true);
    }//GEN-LAST:event_NavbarTransferirMousePressed

    private void NabvarSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NabvarSalirMousePressed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null, "Ha salido de la aplicacion");
       System.exit(0);
    }//GEN-LAST:event_NabvarSalirMousePressed

    private void NabvarHistoTransMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NabvarHistoTransMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        HistorialDeTransferencias hdt = new HistorialDeTransferencias();
        hdt.setVisible(true);
    }//GEN-LAST:event_NabvarHistoTransMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialDeTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialDeTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialDeTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialDeTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialDeTransferencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu NabvarHistoTrans;
    private javax.swing.JMenu NabvarSalir;
    private javax.swing.JMenu NavbarInicio;
    private javax.swing.JMenu NavbarTransferir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
