
package com.pgy.ui;

import com.pgy.business.DatosUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author mauriciomora
 */
public class Inicio extends javax.swing.JFrame {
    
    private String nombreCompleto;
    private int saldo;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setTitle("West Bank");
        mostrarDatosCliente();
    }
    
    public void setDatosCliente(String nombreCompleto, int saldo) {
        this.nombreCompleto = nombreCompleto;
        this.saldo = saldo;
        mostrarDatosCliente();
    }

    private void mostrarDatosCliente() {
        String nombreCompleto = DatosUsuario.getNombreCompleto();
        int saldo = DatosUsuario.getSaldo();

        labelNombreUsuario.setText(nombreCompleto);
        labelSaldo.setText(Integer.toString(saldo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        labelNombreUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        NavbarInicio = new javax.swing.JMenu();
        NavbarTransferir = new javax.swing.JMenu();
        NabvarHisTransf = new javax.swing.JMenu();
        NabvarSalir = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido(a): ");

        labelNombreUsuario.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Tu saldo es:");

        labelSaldo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        NavbarInicio.setText("Inicio");
        NavbarInicio.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NavbarInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NavbarInicioMousePressed(evt);
            }
        });
        jMenuBar1.add(NavbarInicio);

        NavbarTransferir.setText("Transferir");
        NavbarTransferir.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NavbarTransferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NavbarTransferirMousePressed(evt);
            }
        });
        jMenuBar1.add(NavbarTransferir);

        NabvarHisTransf.setText("Historial de transferencias");
        NabvarHisTransf.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NabvarHisTransf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NabvarHisTransfMousePressed(evt);
            }
        });
        jMenuBar1.add(NabvarHisTransf);

        NabvarSalir.setText("Salir");
        NabvarSalir.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NabvarSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NabvarSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(NabvarSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(labelSaldo))
                    .addComponent(labelNombreUsuario)
                    .addComponent(jLabel1))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombreUsuario)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelSaldo))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NabvarSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NabvarSalirMousePressed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null, "Ha salido de la aplicacion");
       System.exit(0);
    }//GEN-LAST:event_NabvarSalirMousePressed

    private void NavbarTransferirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavbarTransferirMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        Transferir transferir = new Transferir();
        transferir.setVisible(true);
    }//GEN-LAST:event_NavbarTransferirMousePressed

    private void NavbarInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavbarInicioMousePressed
        // TODO add your handling code here:

        mostrarDatosCliente();         
    }//GEN-LAST:event_NavbarInicioMousePressed

    private void NabvarHisTransfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NabvarHisTransfMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        HistorialDeTransferencias hdt = new HistorialDeTransferencias();
        hdt.setVisible(true);
    }//GEN-LAST:event_NabvarHisTransfMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu NabvarHisTransf;
    private javax.swing.JMenu NabvarSalir;
    private javax.swing.JMenu NavbarInicio;
    private javax.swing.JMenu NavbarTransferir;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JLabel labelSaldo;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
