
package com.pgy.ui;

import com.pgy.business.DatosUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author mauriciomora
 */
public class Transferir extends javax.swing.JFrame {
    private int numero;

    
    public Transferir() {
        initComponents();
        setTitle("West Bank");
        mostrarDatosCliente();
    }
    
        public void setDatosCliente(int numero) {
        this.numero = numero;
        mostrarDatosCliente();
    }

    private void mostrarDatosCliente() {
        int numero = DatosUsuario.getNumero();
        txtNumCuenta.setText(Integer.toString(numero));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumCuentDesti = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMontoTransf = new javax.swing.JTextField();
        btnTransferir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        NabvarInicio = new javax.swing.JMenu();
        NabvarTransferir = new javax.swing.JMenu();
        NabvarHistoTransf = new javax.swing.JMenu();
        NavbarSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Este es tu numero de cuenta:");

        jLabel2.setText("Ingresa el numero de cuenta de destino");

        txtNumCuentDesti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCuentDestiActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingresa el monto a transferir");

        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        jMenuBar1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        NabvarInicio.setText("Inicio");
        NabvarInicio.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NabvarInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NabvarInicioMousePressed(evt);
            }
        });
        jMenuBar1.add(NabvarInicio);

        NabvarTransferir.setText("Transferir");
        NabvarTransferir.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NabvarTransferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NabvarTransferirMousePressed(evt);
            }
        });
        jMenuBar1.add(NabvarTransferir);

        NabvarHistoTransf.setText("Historial de transferencias");
        NabvarHistoTransf.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NabvarHistoTransf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NabvarHistoTransfMousePressed(evt);
            }
        });
        jMenuBar1.add(NabvarHistoTransf);

        NavbarSalir.setText("Salir");
        NavbarSalir.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        NavbarSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NavbarSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(NavbarSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMontoTransf, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumCuentDesti, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransferir)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumCuenta)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumCuenta))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumCuentDesti, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMontoTransf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTransferir)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumCuentDestiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCuentDestiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCuentDestiActionPerformed

    private void NabvarInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NabvarInicioMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        Inicio inicio = new Inicio();
        inicio.setVisible(true);   
    }//GEN-LAST:event_NabvarInicioMousePressed

    private void NabvarTransferirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NabvarTransferirMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        Transferir transferir = new Transferir();
        transferir.setVisible(true);
    }//GEN-LAST:event_NabvarTransferirMousePressed

    private void NavbarSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavbarSalirMousePressed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null, "Ha salido de la aplicacion");
       System.exit(0);
    }//GEN-LAST:event_NavbarSalirMousePressed

    private void NabvarHistoTransfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NabvarHistoTransfMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        HistorialDeTransferencias hdt = new HistorialDeTransferencias();
        hdt.setVisible(true);
    }//GEN-LAST:event_NabvarHistoTransfMousePressed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransferirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu NabvarHistoTransf;
    private javax.swing.JMenu NabvarInicio;
    private javax.swing.JMenu NabvarTransferir;
    private javax.swing.JMenu NavbarSalir;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField txtMontoTransf;
    private javax.swing.JTextField txtNumCuentDesti;
    private javax.swing.JLabel txtNumCuenta;
    // End of variables declaration//GEN-END:variables
}
